language: node_js

jdk:
  - oraclejdk8

node_js:
  - "7"

script:
  - yarn build
  - yarn test
  - yarn ruling
  - yarn lint
  - yarn license-check
  - ./travis.sh

cache: yarn

notifications:
  email: false
